// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_APPS_MENU_H
#define UI_APPS_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_apps_menu
extern void ui_apps_menu_screen_init(void);
extern void ui_apps_menu_screen_destroy(void);
extern void ui_event_apps_menu(lv_event_t * e);
extern lv_obj_t * ui_apps_menu;
extern lv_obj_t * ui_apps_menu_bg;
extern lv_obj_t * ui_left;
/* App tiles + labels are created dynamically from the loaded entry list
 * (see ui_apps_menu_load_apps); they are no longer individual globals. */
/* ── Dynamic app loading API ─────────────────────────────────────── */
#define APPS_MENU_MAX_APPS  18

typedef struct {
    char         id[32];
    char         name[32];
    const void * icon;
} AppMenuEntry_t;

extern void        ui_apps_menu_load_apps(const AppMenuEntry_t * entries, int count);
extern const char *ui_apps_menu_get_selected_id(void);
extern void        ui_apps_menu_clear_selected(void);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
